name: Deno app build and testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Show version
        id: version
        uses: slackapi/slack-github-action/cli@v2
        with:
          command: "version"

      - name: Deploy
        uses: slackapi/slack-github-action/cli@v2
        with:
          command: "deploy --app A0123456789 --hide-triggers --force"
          token: ${{ secrets.SLACK_SERVICE_TOKEN }}
