name: Deno app build and testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: windows-latest
    timeout-minutes: 5
    defaults:
      run:
        shell: powershell

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install CLI
        run: |
          irm https://downloads.slack-edge.com/slack-cli/install-windows.ps1 | iex
          slack version

      - name: Deploy
        run: |
          slack deploy --app A0123456789
