name: Deno app build and testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Show version
        id: version
        uses: zimeg/slack-github-action/cli@v2.2.0-rc.1
        with:
          command: "version"

      - name: Deploy
        uses: zimeg/slack-github-action/cli@v2.2.0-rc.1
        with:
          command: "deploy --app ${{ vars.SLACK_APP_ID }} --hide-triggers --force"
          token: ${{ secrets.SLACK_SERVICE_TOKEN }}
        env:
          GITHUB_CLIENT_ID: ${{ vars.SLACK_GITHUB_CLIENT_ID }}

      - name: Post a message
        uses: zimeg/slack-github-action@v2.2.0-rc.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Deployed from ${{ matrix.os }}: ${{ github.sha }}"
